Repository lion-packages/dependency-injection, pull requests merged in 2025-03, with the labels that each got.

#21 Update PHPUnit v12
  Dockerfile
  composer.json
  phpunit.xml
Labels: dependencies

#22 Add cache in workflow
  .github/workflows/php.yml
Labels: continuous integration

#23 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration, dependencies

#24 Added dependency-review in Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#25 Added dependabot configuration
  .github/dependabot.yml
Labels: continuous integration

#27 Infection is integrated
  .github/workflows/php.yml
  composer.json
  infection.json
  src/DependencyInjection/Container.php
Labels: continuous integration, dependencies
